name: Contentful Migration Example

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Contentful Migration Example
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v1

    - name: Contentful Migration
      id: migrate
      uses: contentful/contentful-action@v1
      env: # Set the secret as an input
        SPACE_ID: ${{ secrets.SPACE_ID }}
        MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}
        MIGRATIONS_DIR: ${{ secrets.MIGRATIONS_DIR }}

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          See changes to Contentful Enviroment [${{environmentName}} ][1]

          [1]: ${{environmentUrl}}
