name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Migration Testing
    steps:
    - name: Migration
      id: migrate
      uses: shy/contentful-action@master
      with: # Set the secret as an input
        SPACE_ID: ${{ secrets.SPACE_ID }}
        MANGEMENT_API_KEY: ${{ secrets.MANGEMENT_API_KEY }}
